language: python
dist: xenial
sudo: true
services:
  - postgresql
python:
  - 2.7
  - 3.5
  - 3.6
jobs:
  - include:
    - python: 3.6
      env: TOXENV=flake8
install:
  - pip install tox
  - pip install -q tox-travis
script:
    - tox
